//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnoverTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesEntradas
    {
        public Nullable<int> IDVenta { get; set; }
        public Nullable<int> IDEntrada { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Entradas Entradas { get; set; }
        public virtual VentaEntradas VentaEntradas { get; set; }
    }
}
