//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnoverTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entrada()
        {
            this.DetallesEntradas = new HashSet<DetallesEntrada>();
        }
    
        public int IDEntrada { get; set; }
        public Nullable<int> IDConcierto { get; set; }
        public string Localidad { get; set; }
        public int CantidadDisponible { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Concierto Concierto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesEntrada> DetallesEntradas { get; set; }
    }
}
