//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTemperTrap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int FacturaID { get; set; }
        public int IDPedido { get; set; }
        public System.DateTime FechaTransaccion { get; set; }
        public decimal MontoTotal { get; set; }
        public string TipoPago { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
